### ISSUE TITLE
There's a crazy memory leak!

### ISSUE THREAD

**Issue by NodeGuy** [danmarshall/jscad-now#21]
Load `test/index.js` into Brave and do nothing.  Watch memory consumption go up by ~30 MB/s.

**Comment by danmarshall** [comment]
Yikes! Not sure if this is related to Budo https://github.com/mattdesl/budo/issues/213

**Comment by cjnqt** [comment]
Same thing in Safari and Chrome on Mac. Does not seem related to https://github.com/mattdesl/budo/issues/213 because setting `debug: false` does not change anything

**Comment by danmarshall** [comment]
Is it browser or node server side?

**Comment by tonyhschu** [comment]
![Screenshot 2024-01-06 at 9 07 06 AM](https://github.com/danmarshall/jscad-now/assets/929249/af502846-4c6d-4b45-8812-107cbe82efed)

It's on the browser side. This is from running on Chrome.
